"""Write cv/sections.tex (Working Papers and Publications) from _data/papers.yml, so the CV and the site agree.
Run from the repo root or cv/: python cv/make_sections.py, then latexmk -pdf cv.tex in cv/."""
import pathlib
import re

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
d = yaml.safe_load((ROOT / '_data/papers.yml').read_text(encoding='utf-8'))
ME = 'Hyunjoo Yang'


def tex(s):
    s = str(s).replace('\\', r'\textbackslash{}')
    for a, b in [('&', r'\&'), ('%', r'\%'), ('#', r'\#'), ('_', r'\_'), ('$', r'\$')]:
        s = s.replace(a, b)
    s = s.replace('’', "'").replace('“', '``').replace('”', "''")
    return re.sub(r'(\d)–(\d)', r'\1--\2', s)


def authors(a):
    a = [r'\textbf{' + tex(x) + '}' if x == ME else tex(x) for x in a]
    if len(a) <= 1:
        return ''.join(a)
    if len(a) == 2:
        return f'{a[0]} and {a[1]}'
    return ', '.join(a[:-1]) + ', and ' + a[-1]


def citation(x):
    parts = [r'\textbf{' + str(x['year']) + '}'] if x.get('year') else []
    if x.get('journal'):
        j = r'\textbf{' + tex(re.sub(r'\s*\([^)]*[ㄱ-힝][^)]*\)', '', x['journal'])) + '}'   # drop Korean-script aside
        if x.get('volume'):
            j += f", {x['volume']}" + (f"({x['issue']})" if x.get('issue') else '')
        if x.get('pages'):
            j += ', ' + tex(x['pages'])
        parts.append(j)
    if x.get('note'):
        parts.append(f"({tex(x['note'])})")
    return ', '.join(parts)


L = [r'\section*{Working Papers}', '', r'\begin{itemize}']
for i, x in enumerate(d['working_papers']):
    line = r'  \item ' + tex(x['title'])
    if x.get('venue'):
        line += ', ' + tex(x['venue'])
    line += r' \\ ' + r'\textit{' + authors(x['authors']) + '}'
    if x.get('previously'):
        m = re.search(r'abstract_id=(\d+)', x['previously'].get('url', ''))
        line += r' \\ (previously circulated as ``' + tex(x['previously']['title']) + "''" + (
            f', SSRN Working Paper {m.group(1)}' if m else '') + ')'
    L.append(line)
    if i < len(d['working_papers']) - 1:
        L.append(r'  \vspace{3mm}')
L += [r'\end{itemize}', '']
for g in d['publications']:
    name = g['field'] if g['field'].startswith('Computer Science') or g['field'] == 'Book' else 'Publications - ' + g['field']
    L += [r'\section*{' + tex(name) + '}', '', r'\begin{itemize}']
    for i, x in enumerate(g['items']):
        line = r'  \item ' + tex(x['title']) + ', ' + citation(x) + r' \\ \textit{' + authors(x['authors']) + '}'
        if x.get('award'):
            line += r' \\ - \textit{' + tex(x['award']) + '}'
        L.append(line)
        if i < len(g['items']) - 1:
            L.append(r'  \vspace{3mm}')
    L += [r'\end{itemize}', '']
out = pathlib.Path(__file__).resolve().parent / 'sections.tex'
out.write_text('% Generated by make_sections.py from _data/papers.yml. Do not edit by hand.\n' + '\n'.join(L), encoding='utf-8')
print('wrote', out)
